import {Rule} from "sanity";

export const home = {
  name: "home",
  title: "HOME PAGE",
  type: "document",

  fields: [
    {
      name: "heroTitle",
      title: "H1 Hero Title",
      description: "H1 Title",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "heroTitle_de",
      title: "H1 Hero Title German",
      description: "H1 Title",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "heroTitle_es",
      title: "H1 Hero Title Spanish",
      description: "H1 Title",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "heroTitle_fr",
      title: "H1 Hero Title French",
      description: "H1 Title",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "heroTitle_it",
      title: "H1 Hero Title Italian",
      description: "H1 Title",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "heroTitle_pt",
      title: "H1 Hero Title Portuguese",
      description: "H1 Title",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "heroText",
      title: "Hero Text",
      description: "Main text for the hero section.",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "heroText_de",
      title: "Hero Text German",
      description: "Main text for the hero section.",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "heroText_es",
      title: "Hero Text Spanish",
      description: "Main text for the hero section.",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "heroText_fr",
      title: "Hero Text French",
      description: "Main text for the hero section.",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "heroText_it",
      title: "Hero Text Italian",
      description: "Main text for the hero section.",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "heroText_pt",
      title: "Hero Text Portuguese",
      description: "Main text for the hero section.",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "heroTextUnderButton",
      title: "Small Hero Text Under Button",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "heroTextUnderButton_de",
      title: "Small Hero Text Under Button German",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "heroTextUnderButton_es",
      title: "Small Hero Text Under Button Spanish",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "heroTextUnderButton_fr",
      title: "Small Hero Text Under Button French",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "heroTextUnderButton_it",
      title: "Small Hero Text Under Button Italian",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "heroTextUnderButton_pt",
      title: "Small Hero Text Under Button Portuguese",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "sectionThreeTitle",
      title: "H2 Section Three Title",
      description: "H2 Title In Section Three",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionThreeTitle_de",
      title: "H2 Section Three Title German",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionThreeTitle_es",
      title: "H2 Section Three Title Spanish",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionThreeTitle_fr",
      title: "H2 Section Three Title French",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionThreeTitle_it",
      title: "H2 Section Three Title Italian",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionThreeTitle_pt",
      title: "H2 Section Three Title Portuguese",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "sectionThreeText",
      title: "Section Three Text",
      description: "Text under H2 Title in Section Three.",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionThreeText_de",
      title: "Section Three Text German",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionThreeText_es",
      title: "Section Three Text Spanish",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionThreeText_fr",
      title: "Section Three Text French",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionThreeText_it",
      title: "Section Three Text Italian",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionThreeText_pt",
      title: "Section Three Text Portuguese",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "sectionThreeStarsNumber",
      title: "Section Three Stars Number",
      description: "Section Three Stars Number",
      type: "number",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "sectionThreeTextUnderStarsNumber",
      title: "Section Three Text Under Stars Number",
      description: "Section Three Text Under Stars Number",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionThreeTextUnderStarsNumber_de",
      title: "Section Three Text Under Stars Number German",
      description: "Section Three Text Under Stars Number",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionThreeTextUnderStarsNumber_es",
      title: "Section Three Text Under Stars Number Spanish",
      description: "Section Three Text Under Stars Number",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionThreeTextUnderStarsNumber_fr",
      title: "Section Three Text Under Stars Number French",
      description: "Section Three Text Under Stars Number",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionThreeTextUnderStarsNumber_it",
      title: "Section Three Text Under Stars Number Italian",
      description: "Section Three Text Under Stars Number",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionThreeTextUnderStarsNumber_pt",
      title: "Section Three Text Under Stars Number Portuguese",
      description: "Section Three Text Under Stars Number",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "sectionThreeUsersNumber",
      title: "Section Three Users Number",
      description: "Section Three Users Number",
      type: "number",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "sectionThreeTextUnderUsersNumber",
      title: "Section Three Text Under Users Number",
      description: "Section Three Text Under Users Number",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionThreeTextUnderUsersNumber_de",
      title: "Section Three Text Under Users Number German",
      description: "Section Three Text Under Users Number",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionThreeTextUnderUsersNumber_es",
      title: "Section Three Text Under Users Number Spanish",
      description: "Section Three Text Under Users Number",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionThreeTextUnderUsersNumber_fr",
      title: "Section Three Text Under Users Number French",
      description: "Section Three Text Under Users Number",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionThreeTextUnderUsersNumber_it",
      title: "Section Three Text Under Users Number Italian",
      description: "Section Three Text Under Users Number",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionThreeTextUnderUsersNumber_pt",
      title: "Section Three Text Under Users Number Portuguese",
      description: "Section Three Text Under Users Number",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "sectionThreeTimeNumber",
      title: "Section Three Time Number",
      description: "Section Three Time Number",
      type: "number",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "sectionThreeTextUnderTimeNumber",
      title: "Section Three Text Under Time Number",
      description: "Section Three Text Under Time Number",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionThreeTextUnderTimeNumber_de",
      title: "Section Three Text Under Time Number German",
      description: "Section Three Text Under Time Number",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionThreeTextUnderTimeNumber_es",
      title: "Section Three Text Under Time Number Spanish",
      description: "Section Three Text Under Time Number",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionThreeTextUnderTimeNumber_fr",
      title: "Section Three Text Under Time Number French",
      description: "Section Three Text Under Time Number",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionThreeTextUnderTimeNumber_it",
      title: "Section Three Text Under Time Number Italian",
      description: "Section Three Text Under Time Number",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionThreeTextUnderTimeNumber_pt",
      title: "Section Three Text Under Time Number Portuguese",
      description: "Section Three Text Under Time Number",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "sliderTitle",
      title: "H2 Slider Title",
      description: "H2 Slider Title",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sliderTitle_de",
      title: "Slider Title German",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sliderTitle_es",
      title: "Slider Title Spanish",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sliderTitle_fr",
      title: "Slider Title French",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sliderTitle_it",
      title: "Slider Title Italian",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sliderTitle_pt",
      title: "Slider Title Portuguese",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "sliderText",
      title: "Slider Text",
      description: "Slider Text under Title",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sliderText_de",
      title: "Slider Text German",
      description: "Slider Text under Title",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sliderText_es",
      title: "Slider Text Spanish",
      description: "Slider Text under Title",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sliderText_fr",
      title: "Slider Text French",
      description: "Slider Text under Title",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sliderText_it",
      title: "Slider Text Italian",
      description: "Slider Text under Title",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sliderText_pt",
      title: "Slider Text Portuguese",
      description: "Slider Text under Title",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "sliderAverageMonthlyIncome",
      title: "Slider Average Monthly Income",
      description: "Slider Average Monthly Income",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sliderAverageMonthlyIncome_de",
      title: "Slider Average Monthly Income German",
      description: "Slider Average Monthly Income",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sliderAverageMonthlyIncome_es",
      title: "Slider Average Monthly Income Spanish",
      description: "Slider Average Monthly Income",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sliderAverageMonthlyIncome_fr",
      title: "Slider Average Monthly Income French",
      description: "Slider Average Monthly Income",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sliderAverageMonthlyIncome_it",
      title: "Slider Average Monthly Income Italian",
      description: "Slider Average Monthly Income",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sliderAverageMonthlyIncome_pt",
      title: "Slider Average Monthly Income Portuguese",
      description: "Slider Average Monthly Income",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "reviewsText",
      title: "Review Text",
      description: "Review Text on top of video component",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "reviewsText_de",
      title: "Review Text German",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "reviewsText_es",
      title: "Review Text Spanish",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "reviewsText_fr",
      title: "Review Text French",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "reviewsText_it",
      title: "Review Text Italian",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "reviewsText_pt",
      title: "Review Text Portuguese",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "sectionSixTitle",
      title: "H2 Section Six Title",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionSixTitle_de",
      title: "Section Six Title German",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionSixTitle_es",
      title: "Section Six Title Spanish",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionSixTitle_fr",
      title: "Section Six Title French",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionSixTitle_it",
      title: "Section Six Title Italian",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionSixTitle_pt",
      title: "Section Six Title Portuguese",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "sectionSevenTitle",
      title: "H2 Section Seven Title",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionSevenTitle_de",
      title: "Section Seven Title German",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionSevenTitle_es",
      title: "Section Seven Title Spanish",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionSevenTitle_fr",
      title: "Section Seven Title French",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionSevenTitle_it",
      title: "Section Seven Title Italian",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionSevenTitle_pt",
      title: "Section Seven Title Portuguese",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "sectionSevenText",
      title: "Section Seven Text",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionSevenText_de",
      title: "Section Seven Text German",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionSevenText_es",
      title: "Section Seven Text Spanish",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionSevenText_fr",
      title: "Section Seven Text French",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionSevenText_it",
      title: "Section Seven Text Italian",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionSevenText_pt",
      title: "Section Seven Text Portuguese",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "sectionSevenSubTitleOne",
      title: "H3 Section Seven Sub Title One",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionSevenSubTitleOne_de",
      title: "Section Seven Sub Title One German",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionSevenSubTitleOne_es",
      title: "Section Seven Sub Title One Spanish",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionSevenSubTitleOne_fr",
      title: "Section Seven Sub Title One French",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionSevenSubTitleOne_it",
      title: "Section Seven Sub Title One Italian",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionSevenSubTitleOne_pt",
      title: "Section Seven Sub Title One Portuguese",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "sectionFourteenTitle",
      title: "H2 Section Fourteen Title",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionFourteenTitle_de",
      title: "Section Fourteen Title German",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionFourteenTitle_es",
      title: "Section Fourteen Title Spanish",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionFourteenTitle_fr",
      title: "Section Fourteen Title French",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionFourteenTitle_it",
      title: "Section Fourteen Title Italian",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "sectionFourteenTitle_pt",
      title: "Section Fourteen Title Portuguese",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "metaTitle",
      title: "Meta Title",
      description: "Meta Title for home page",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "metaTitle_de",
      title: "Meta Title German",
      description: "Meta Title for home page",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "metaTitle_es",
      title: "Meta Title Spanish",
      description: "Meta Title for home page",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "metaTitle_fr",
      title: "Meta Title French",
      description: "Meta Title for home page",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "metaTitle_it",
      title: "Meta Title Italian",
      description: "Meta Title for home page",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "metaTitle_pt",
      title: "Meta Title Portuguese",
      description: "Meta Title for home page",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "metaDescription",
      title: "Meta Description",
      description: "Meta Description for home page",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "metaDescription_de",
      title: "Meta Description German",
      description: "Meta Description for home page",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "metaDescription_es",
      title: "Meta Description Spanish",
      description: "Meta Description for home page",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "metaDescription_fr",
      title: "Meta Description French",
      description: "Meta Description for home page",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "metaDescription_it",
      title: "Meta Description Italian",
      description: "Meta Description for home page",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },
    {
      name: "metaDescription_pt",
      title: "Meta Description Portuguese",
      description: "Meta Description for home page",
      type: "string",
      validation: (Rule: Rule) => Rule.required().error("Required"),
    },

    {
      name: "keywords",
      title: "SEO Keywords",
      description: "Keywords for SEO Home Page.",
      type: "array",
      of: [{type: "string"}],
      options: {
        layout: "tags",
      },
      validation: (Rule: Rule) => Rule.required().min(1).error("At least one keyword is required"),
    },
  ],
};
